server:
  port: 10001
spring:
  application:
    name: wf-mp
  mvc:
    pathmatch:
      # Springfox使用的路径匹配是基于AntPathMatcher的，而Spring Boot 2.6.X使用的是PathPatternMatcher
      matching-strategy: ant_path_matcher
  knife4j:
    enable: true #开启增强配置
    basic: #基本的登录认证
      enable: true
      username: admin
      password: 123456
  datasource:
    url: jdbc:mysql://localhost:3306/mp_db?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true&allowMultiQueries=true

    driver-class-name: com.mysql.cj.jdbc.Driver
    username: testuser
    password: 123456

mybatis-plus:
  type-aliases-package: com.wf.mp.domain.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/*.xml


